USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS MCP_HOL;
CREATE SCHEMA IF NOT EXISTS MCP_HOL.SUPPORT;
CREATE SCHEMA IF NOT EXISTS MCP_HOL.AGENTS;

CREATE ROLE IF NOT EXISTS CUSTOMER_AGENT;

GRANT USAGE ON DATABASE MCP_HOL TO ROLE CUSTOMER_AGENT;
GRANT USAGE ON SCHEMA MCP_HOL.SUPPORT TO ROLE CUSTOMER_AGENT;
GRANT USAGE ON SCHEMA MCP_HOL.AGENTS TO ROLE CUSTOMER_AGENT;
GRANT USAGE ON WAREHOUSE COCO_WH TO ROLE CUSTOMER_AGENT;